 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dining_venues", type: :request do
  
  # DiningVenue. As you add validations to DiningVenue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DiningVenue.create! valid_attributes
      get dining_venues_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dining_venue = DiningVenue.create! valid_attributes
      get dining_venue_url(dining_venue)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dining_venue_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dining_venue = DiningVenue.create! valid_attributes
      get edit_dining_venue_url(dining_venue)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DiningVenue" do
        expect {
          post dining_venues_url, params: { dining_venue: valid_attributes }
        }.to change(DiningVenue, :count).by(1)
      end

      it "redirects to the created dining_venue" do
        post dining_venues_url, params: { dining_venue: valid_attributes }
        expect(response).to redirect_to(dining_venue_url(DiningVenue.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DiningVenue" do
        expect {
          post dining_venues_url, params: { dining_venue: invalid_attributes }
        }.to change(DiningVenue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dining_venues_url, params: { dining_venue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dining_venue" do
        dining_venue = DiningVenue.create! valid_attributes
        patch dining_venue_url(dining_venue), params: { dining_venue: new_attributes }
        dining_venue.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dining_venue" do
        dining_venue = DiningVenue.create! valid_attributes
        patch dining_venue_url(dining_venue), params: { dining_venue: new_attributes }
        dining_venue.reload
        expect(response).to redirect_to(dining_venue_url(dining_venue))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dining_venue = DiningVenue.create! valid_attributes
        patch dining_venue_url(dining_venue), params: { dining_venue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dining_venue" do
      dining_venue = DiningVenue.create! valid_attributes
      expect {
        delete dining_venue_url(dining_venue)
      }.to change(DiningVenue, :count).by(-1)
    end

    it "redirects to the dining_venues list" do
      dining_venue = DiningVenue.create! valid_attributes
      delete dining_venue_url(dining_venue)
      expect(response).to redirect_to(dining_venues_url)
    end
  end
end
