class AddManyAttrsToCachedTouringplansAttractions < ActiveRecord::Migration[6.1]
  def change
    add_column :cached_touringplans_attractions, :open_emh_morning, :boolean
    add_column :cached_touringplans_attractions, :single_rider, :boolean
    add_column :cached_touringplans_attractions, :time_zone, :string
    add_column :cached_touringplans_attractions, :seasonal, :boolean
    add_column :cached_touringplans_attractions, :open_very_merry, :boolean
    add_column :cached_touringplans_attractions, :open_not_so_scary, :boolean
    add_column :cached_touringplans_attractions, :category_code, :string
    add_column :cached_touringplans_attractions, :scheduled_code, :string
    add_column :cached_touringplans_attractions, :duration, :float
    add_column :cached_touringplans_attractions, :what_it_is, :string
    add_column :cached_touringplans_attractions, :scope_and_scale_code, :string
    add_column :cached_touringplans_attractions, :when_to_go, :string
    add_column :cached_touringplans_attractions, :average_wait_per_hundred, :float
    add_column :cached_touringplans_attractions, :average_wait_assumes, :string
    add_column :cached_touringplans_attractions, :loading_speed, :string
    add_column :cached_touringplans_attractions, :probable_wait_time, :string
    add_column :cached_touringplans_attractions, :special_needs, :string
    add_column :cached_touringplans_attractions, :height_restriction, :integer
    add_column :cached_touringplans_attractions, :intense, :boolean
    add_column :cached_touringplans_attractions, :extinct_on, :datetime
    add_column :cached_touringplans_attractions, :opened_on, :datetime
    add_column :cached_touringplans_attractions, :frightening, :boolean
    add_column :cached_touringplans_attractions, :physical_considerations, :boolean
    add_column :cached_touringplans_attractions, :handheld_captioning, :boolean
    add_column :cached_touringplans_attractions, :video_captioning, :boolean
    add_column :cached_touringplans_attractions, :reflective_captioning, :boolean
    add_column :cached_touringplans_attractions, :assistive_listening, :boolean
    add_column :cached_touringplans_attractions, :audio_description, :boolean
    add_column :cached_touringplans_attractions, :wheelchair_transfer_code, :string
    add_column :cached_touringplans_attractions, :no_service_animals, :boolean
    add_column :cached_touringplans_attractions, :sign_language, :boolean
    add_column :cached_touringplans_attractions, :service_animal_check, :boolean
    add_column :cached_touringplans_attractions, :not_to_be_missed, :boolean
    add_column :cached_touringplans_attractions, :rider_swap, :boolean
    add_column :cached_touringplans_attractions, :park_entrance, :boolean
    add_column :cached_touringplans_attractions, :ultimate_code, :string
    add_column :cached_touringplans_attractions, :ultimate_task, :string
    add_column :cached_touringplans_attractions, :close_at_dusk, :boolean
    add_column :cached_touringplans_attractions, :crowd_calendar_version, :integer
    add_column :cached_touringplans_attractions, :match_name, :boolean
    add_column :cached_touringplans_attractions, :crazy_threshold, :boolean
    add_column :cached_touringplans_attractions, :fastpass_only, :boolean
    add_column :cached_touringplans_attractions, :allow_showtimes_after_close, :boolean
    add_column :cached_touringplans_attractions, :disconnected_fastpass_booth, :boolean
    add_column :cached_touringplans_attractions, :arrive_before, :integer
    add_column :cached_touringplans_attractions, :arrive_before_fp, :integer
    add_column :cached_touringplans_attractions, :allow_time_restriction, :boolean
    add_column :cached_touringplans_attractions, :relative_open_to_sunset, :integer
    add_column :cached_touringplans_attractions, :relative_close_to_sunset, :integer
    add_column :cached_touringplans_attractions, :closing_round_code, :string
    add_column :cached_touringplans_attractions, :walking_time_proxy_id, :integer
    add_column :cached_touringplans_attractions, :operator_id, :integer
    add_column :cached_touringplans_attractions, :operator_type, :string
    add_column :cached_touringplans_attractions, :hide_app, :boolean
    add_column :cached_touringplans_attractions, :showtime_proxy_id, :integer
    add_column :cached_touringplans_attractions, :sort_name, :string
    add_column :cached_touringplans_attractions, :extinct_on_uncertain, :boolean
    add_column :cached_touringplans_attractions, :opened_on_uncertain, :boolean
    add_column :cached_touringplans_attractions, :ignore_scrapes, :boolean
    add_column :cached_touringplans_attractions, :extra_cost, :boolean
    add_column :cached_touringplans_attractions, :climate_controlled, :boolean
    add_column :cached_touringplans_attractions, :wet, :boolean
    add_column :cached_touringplans_attractions, :operational_notes, :text
    add_column :cached_touringplans_attractions, :latitude, :string
    add_column :cached_touringplans_attractions, :longitude, :string
    add_column :cached_touringplans_attractions, :open_early, :boolean
    add_column :cached_touringplans_attractions, :themeparks_entity_id, :string
    add_column :cached_touringplans_attractions, :has_virtual_queue, :boolean
  end
end
